### ISSUE TITLE
Plugin no longer works on Nodebb version 3.x

### ISSUE THREAD

**Issue by DroidBV8** [MinecraftForgeFrance/nodebb-plugin-extended-markdown#8] opened 2023-04-19 12:53 UTC
Hello @robin4002 @Woryk @Phenix246 @Superloup10  :)

the plugin no longer works on **Nodebb version 3.x** (RC2) with the new Harmony theme

Is there any intention to make this plugin v3 compatible?

Thans for your answer

**Comment by robin4002** [comment] 2023-04-25 11:26
Hi,
Thanks for your report. I will update all plugins used in my forum when I have enough time, hopefully before NodeBB 3.0 is released as stable!

**Comment by lmalma** [comment] 2023-05-01 09:28
Is there an estimate of when you will be able to update your plugins?
We're all waiting for it, especially for the spoiler button that hides content, but doesn't show it when the button is pressed.

**Comment by DroidBV8** [comment] 2023-05-01 09:54
@robin

I have open a thread here :

https://community.nodebb.org/topic/17134/nodebb-plugin-extended-markdown-not-v3-comaptible/3

I had asked him to make an official fork of this plugin in case you do not respond or if you do not update it.

Baris the develloper of nodeBB tell this :

I see you opened an issue on their repo, so let's wait and see if they respond before forking. The plugin seems simple and doesn't even have an admin page, so the only thing I can see that needs updating for 3.x is to update style.less to styles.scss.

**Comment by robin4002** [comment] 2023-05-02 21:04
I did setup NodeBB 3 on my local environment, I will work on it tomorrow. 
Since @Veronikya already did some work in PR#9 I hope the update will be fast.

**Comment by robin4002** [comment] 2023-05-03 20:53
dcb3e29beaa38454c36dfcfd192a5c496dfc3c7b
The new version is published 🎉 
https://www.npmjs.com/package/nodebb-plugin-extended-markdown/v/2.0.0
I quickly tested features, the tooltip is half-broken (bootstrap tooltip doesn't show, but the browser still shows a text if you keep the mouse on). I need more time to fix it.
Other features are ok, if you find any issue let me know!

**Comment by ShlomoCode** [comment] 2023-05-19 14:09
@robin4002 The plugin doesn't work for me with Nodbibi 3.1.4, the buttons don't click at all
When composer is loaded, the error appears in the console:
```
nodebb.min.js?v=4out31m1dpv:8 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
     at nodebb.min.js?v=4out31m1dpv:8:6683
```

And it seems to be related to the plugin:
![CleanShot 2023-05-19 at 17 05 59@2x](https://github.com/MinecraftForgeFrance/nodebb-plugin-extended-markdown/assets/78599753/78a272f3-6bc0-48d4-8183-1291bb4738c2)

The problem is in both the Persona and Harmony themes

**Comment by DroidBV8** [comment] 2023-05-21 09:02
Same here, plugin doesn't work on NodeBB 3.1.4

**Comment by DroidBV8** [comment] 2023-05-22 18:26
@robin4002

**Comment by robin4002** [comment] 2023-05-23 09:41
I will take a look this week.

**Comment by robin4002** [comment] 2023-05-26 22:02
This change on the composer : https://github.com/NodeBB/nodebb-plugin-composer-default/commit/19dd564c2f816997195f9ac5fc46cc21b8295f84 is the cause of the problem.
Editor actions were inside a <a> element, now they are directly in <li> element. I published the new release 2.0.1 to fix it.

**Comment by ShlomoCode** [comment] 2023-05-27 18:23
@robin4002 Thanks, fixed it for me

**Comment by robin4002** [comment] 2024-04-02 18:30
I close the ticket as the problem is resolved.

**Closed by robin4002** 2024-04-02 18:30 UTC
